image: docker.uib.gmbh/opsi/dev/pybuilder:uib-python-default

stages:
  - build
  - package

build:linux-pyinstaller:
  stage: build
  script:
    - poetry install
    - poetry run opsi-dev-tool -l info --pyinstaller-poetry-build
    - '[ "$CI_COMMIT_TAG" = "" ] && opsi-dev-tool -l info --binary-push dist/opsi-hwaudit "$CI_JOB_ID"'
    - '[ "$CI_COMMIT_TAG" = "" ] || opsi-dev-tool -l info --binary-push dist/opsi-hwaudit'
  artifacts:
    name: 'hwaudit-linux-pyinstaller'
    paths:
      - dist/opsi-hwaudit
    expire_in: 2 day

build:windows-pyinstaller:
  stage: build
  tags:
    - win10
  script:
    - pip install poetry
    - poetry remove mysqlclient
    - poetry add "deps/mysqlclient-1.4.6-cp37-cp37m-win32.whl"
    - poetry update mysqlclient
    - poetry run opsi-dev-tool -l info --pyinstaller-poetry-build
    - poetry run opsi-dev-tool -l info --signserver-sign dist\opsi-hwaudit.exe
    - if (! $CI_COMMIT_TAG) {poetry run opsi-dev-tool -l info --binary-push dist\opsi-hwaudit.exe "$CI_JOB_ID"}
    - if ($CI_COMMIT_TAG) {poetry run opsi-dev-tool -l info --binary-push dist\opsi-hwaudit.exe}
  artifacts:
    name: 'hwaudit-windows-pyinstaller'
    paths:
      - dist\opsi-hwaudit.exe
    expire_in: 2 day

build:osx-pyinstaller:
  stage: build
  tags:
    - macostest
  script:
    - source $HOME/.poetry/env
    - poetry install
    - poetry run opsi-dev-tool -l info --pyinstaller-poetry-build
    - '[ "$CI_COMMIT_TAG" = "" ] && poetry run opsi-dev-tool -l info --binary-push dist/opsi-hwaudit "$CI_JOB_ID"'
    - '[ "$CI_COMMIT_TAG" = "" ] || poetry run opsi-dev-tool -l info --binary-push dist/opsi-hwaudit'
  artifacts:
    name: 'hwaudit-macos-pyinstaller'
    paths:
      - dist/opsi-hwaudit
    expire_in: 2 day

package:makeopsipackage:
  stage: package
  script:
    - version=`cat pyproject.toml | grep -e "^version = " | cut -d \" -f 2`
    - cat hwaudit-opsi-package/OPSI/control | awk -v new_version="$version" '/^\[/ { section=$1} {line=$0; if ($1 == "version:" && section == "[Product]"){ line = $1 " " new_version} print line}' > tmp
    - cat tmp > hwaudit-opsi-package/OPSI/control
    - rm tmp
    - opsi-dev-tool -l debug --binary-pull
    - version=`grep hwaudit-opsi-package/OPSI/control -A 10 -e "\[Product\]" | grep "version:" | tr -d "^a-zA-Z :"`
    - package=`grep hwaudit-opsi-package/OPSI/control -A 5 -e "\[Package\]" | grep "version:" | tr -d "^a-zA-Z :"`
    - '[ "$CI_COMMIT_TAG" = "" ] && sed -i "s/version: $package/version: $package.$CI_JOB_ID/" hwaudit-opsi-package/OPSI/control'
    - opsi-makepackage --no-set-rights -l 6 hwaudit-opsi-package
    - upload-package hwaudit*.opsi

  artifacts:
    name: hwaudit-opsi-package
    paths:
      - "hwaudit_*.opsi*"
