image: docker.uib.gmbh/opsi/dev/pybuilder:deb9-py3.11

stages:
  - test
  - build
  - package
  - integration_test


lint:
  stage: test
  script:
    - uv run ruff check hwaudit
    - uv run mypy hwaudit


linux-pyinstaller:
  stage: build
  script:
    - export UV_PYTHON_PREFERENCE="only-managed"
    - export UV_PYTHON="3.13"
    - opsi-dev-cli self upgrade
    - uv self update
    - uv sync --frozen
    - uv run opsi-dev-cli -l debug pyinstaller build
    - dist/opsi-hwaudit --help
    - '[ "$CI_COMMIT_TAG" = "" ] && opsi-dev-cli -l info binary push dist/opsi-hwaudit --prerelease="$CI_JOB_ID"'
    - '[ "$CI_COMMIT_TAG" = "" ] || opsi-dev-cli -l info binary push dist/opsi-hwaudit'


windows-pyinstaller:
  stage: build
  tags:
    - win10-py311-x86
  script:
    - $Env:UV_PYTHON_INSTALL_DIR = "c:\\uv\\python"
    - $Env:UV_CACHE_DIR = "c:\\uv\\cache"
    - $Env:UV_PYTHON = ((uv python list --managed-python --all-arches | findstr 3.13 | findstr "\-x86\-" | findstr /v freethreaded) -split ' ')[0]
    - $Env:UV_PYTHON_PREFERENCE = "only-managed"
    - powershell -ExecutionPolicy ByPass -c "irm http://binaryindex.uib.gmbh/development/opsi-dev-tools/windows/x86/installer.ps1 | iex"
    - uv sync --frozen
    - uv run opsi-dev-cli -l debug pyinstaller build
    - opsi-dev-cli -l info signserver sign dist\opsi-hwaudit.exe
    - dist\opsi-hwaudit.exe --help
    - if (! $CI_COMMIT_TAG) {opsi-dev-cli -l info binary push dist\opsi-hwaudit.exe --prerelease="$CI_JOB_ID"}
    - if ($CI_COMMIT_TAG) {opsi-dev-cli -l info binary push dist\opsi-hwaudit.exe}


osx-pyinstaller:
  stage: build
  tags:
    - catalina-py311-x64
  script:
    - export UV_PYTHON_PREFERENCE="only-managed"
    - export UV_PYTHON="3.13"
    - curl http://binaryindex.uib.gmbh/development/opsi-dev-tools/darwin/x64/installer.sh | sh
    - uv self update
    - uv sync --frozen
    - uv run opsi-dev-cli -l debug pyinstaller build
    - dist/opsi-hwaudit --help
    - '[ "$CI_COMMIT_TAG" = "" ] && opsi-dev-cli -l info binary push dist/opsi-hwaudit --prerelease="$CI_JOB_ID"'
    - '[ "$CI_COMMIT_TAG" = "" ] || opsi-dev-cli -l info binary push dist/opsi-hwaudit'


makeopsipackage:
  stage: package
  script:
    - export version=$(opsi-dev-cli project info version)
    - newpackage=$(opsi-dev-cli -l 6 opsi-package get-value packageVersion)
    - '[ "$CI_COMMIT_TAG" = "" ] && newpackage="$newpackage.$CI_JOB_ID"'
    - opsi-dev-cli -l 5 opsi-package set-value packageVersion "$newpackage"
    - opsi-dev-cli -l 5 opsi-package set-value productVersion "$version"
    - opsi-dev-cli -l 6 binary pull
    - opsi-dev-cli changelog from-git output
    - cp output/changelog.md OPSI/CHANGELOG.md
    - opsi-cli -l6 package make
    - upload-package hwaudit*.opsi
  artifacts:
    name: prepared_files
    paths:
      - OPSI/control

test_tagged_manual:
  stage: integration_test
  when: manual
  script:
    - version=$(opsi-dev-cli opsi-package get-value productVersion)
    - package=$(opsi-dev-cli opsi-package get-value packageVersion)
    - version="$version-$(echo $package | tr '.' '~')"
    - opsi-dev-cli -l info jenkins test --versions="$version"

test_tagged:
  stage: integration_test
  only:
    - tags
  script:
    - version=$(opsi-dev-cli opsi-package get-value productVersion)
    - package=$(opsi-dev-cli opsi-package get-value packageVersion)
    - version="$version-$(echo $package | tr '.' '~')"
    - opsi-dev-cli -l info jenkins test --versions="$version"
