image: docker.uib.gmbh/opsi/dev/pybuilder:uib-python-default

stages:
  - build
  - package

linux-pyinstaller:
  stage: build
  script:
    - poetry install
    - poetry run opsi-dev-cli -l info pyinstaller build
    - dist/opsi-hwaudit --help
    - '[ "$CI_COMMIT_TAG" = "" ] && opsi-dev-tool -l info binary push dist/opsi-hwaudit --prerelease="$CI_JOB_ID"'
    - '[ "$CI_COMMIT_TAG" = "" ] || opsi-dev-tool -l info binary push dist/opsi-hwaudit'


windows-pyinstaller:
  stage: build
  tags:
    - win10
  script:
    - Invoke-WebRequest -UseBasicParsing -Uri "$OPSIDEVTOOLS_URL_WINDOWS_X86" -OutFile opsi-dev-tools.zip
    - Expand-Archive opsi-dev-tools.zip -DestinationPath .
    - .\opsi-dev-tool.exe --self-install -l info
    - poetry install
    - poetry run .\opsi-dev-cli.exe -l info pyinstaller build
    - poetry run .\opsi-dev-tool.exe -l info --signserver-sign dist\opsi-hwaudit.exe
    - dist\opsi-hwaudit.exe --help
    - if (! $CI_COMMIT_TAG) {poetry run opsi-dev-cli.exe -l info binary push dist\opsi-hwaudit.exe --prerelease="$CI_JOB_ID"}
    - if ($CI_COMMIT_TAG) {poetry run opsi-dev-cli.exe -l info binary push dist\opsi-hwaudit.exe}


osx-pyinstaller:
  stage: build
  tags:
    - macos
  script:
    - curl -o opsi-dev-tools.tar.gz "$OPSIDEVTOOLS_URL_DARWIN_X64"
    - tar -xvf opsi-dev-tools.tar.gz
    - ./opsi-dev-tool --self-install
    - poetry install
    - poetry run opsi-dev-cli -l info pyinstaller build
    - dist/opsi-hwaudit --help
    - '[ "$CI_COMMIT_TAG" = "" ] && poetry run opsi-dev-cli -l info binary push dist/opsi-hwaudit --prerelease="$CI_JOB_ID"'
    - '[ "$CI_COMMIT_TAG" = "" ] || poetry run opsi-dev-cli -l info binary push dist/opsi-hwaudit'


makeopsipackage:
  stage: package
  script:
    - export version=`cat pyproject.toml | grep -e "^version = " | cut -d \" -f 2`
    - cat hwaudit-opsi-package/OPSI/control | awk -v new_version="$version" '/^\[/ { section=$1} {line=$0; if ($1 == "version:" && section == "[Product]"){ line = $1 " " new_version} print line}' > tmp
    - cat tmp > hwaudit-opsi-package/OPSI/control
    - rm tmp
    - opsi-dev-cli -l info binary pull
    - 'sed -i "/Product/,/version:/s/version: .*\$/version: $version/" hwaudit-opsi-package/OPSI/control' # true version in pyproject.toml
    - package=`grep hwaudit-opsi-package/OPSI/control -A 5 -e "\[Package\]" | grep "version:" | tr -d "^a-zA-Z :"` # true package in OPSI/control
    - '[ "$CI_COMMIT_TAG" = "" ] && sed -i "s/version: $package/version: $package.$CI_JOB_ID/" hwaudit-opsi-package/OPSI/control'
    - opsi-makepackage --no-set-rights -l 6 hwaudit-opsi-package
    - upload-package hwaudit*.opsi true true true false
