image: docker.uib.gmbh/opsi/dev/pybuilder:uib-python-default

stages:
  - test
  - build
  - package


lint:
  stage: test
  script:
    - poetry lock --no-update
    - poetry install
    - poetry run ruff hwaudit
    - poetry run mypy hwaudit


linux-pyinstaller:
  stage: build
  script:
    - poetry lock --no-update
    - poetry install
    - poetry run opsi-dev-cli -l info pyinstaller build
    - dist/opsi-hwaudit --help
    - '[ "$CI_COMMIT_TAG" = "" ] && opsi-dev-cli -l info binary push dist/opsi-hwaudit --prerelease="$CI_JOB_ID"'
    - '[ "$CI_COMMIT_TAG" = "" ] || opsi-dev-cli -l info binary push dist/opsi-hwaudit'


windows-pyinstaller:
  stage: build
  tags:
    - win10-py311-x86
  script:
    - Invoke-WebRequest -UseBasicParsing -Uri "$OPSIDEVTOOLS_URL_WINDOWS_X86" -OutFile opsi-dev-tools.zip
    - Expand-Archive opsi-dev-tools.zip -DestinationPath .
    - Copy-Item opsi-dev-tool.exe opsi-dev-cli.exe
    - poetry lock --no-update
    - poetry install
    - poetry run .\opsi-dev-cli.exe -l info pyinstaller build
    - poetry run .\opsi-dev-tool.exe -l info --signserver-sign dist\opsi-hwaudit.exe
    - dist\opsi-hwaudit.exe --help
    - if (! $CI_COMMIT_TAG) {poetry run .\opsi-dev-cli.exe -l info binary push dist\opsi-hwaudit.exe --prerelease="$CI_JOB_ID"}
    - if ($CI_COMMIT_TAG) {poetry run .\opsi-dev-cli.exe -l info binary push dist\opsi-hwaudit.exe}


osx-pyinstaller:
  stage: build
  tags:
    - catalina-py311-x64
  script:
    - curl -o opsi-dev-tools.tar.gz "$OPSIDEVTOOLS_URL_DARWIN_X64"
    - tar -xvf opsi-dev-tools.tar.gz
    - mv opsi-dev-tool opsi-dev-cli
    - poetry lock --no-update
    - poetry install
    - poetry run ./opsi-dev-cli -l info pyinstaller build
    - dist/opsi-hwaudit --help
    - '[ "$CI_COMMIT_TAG" = "" ] && poetry run ./opsi-dev-cli -l info binary push dist/opsi-hwaudit --prerelease="$CI_JOB_ID"'
    - '[ "$CI_COMMIT_TAG" = "" ] || poetry run ./opsi-dev-cli -l info binary push dist/opsi-hwaudit'


makeopsipackage:
  stage: package
  script:
    - export version=$(cat pyproject.toml | grep -e "^version = " | cut -d \" -f 2)
    - opsi-dev-cli -l 6 opsi-package --path=hwaudit-opsi-package set-value productVersion "$version"
    - export package=$(opsi-dev-cli -l 6 opsi-package --path=hwaudit-opsi-package get-value packageVersion)
    - '[ "$CI_COMMIT_TAG" = "" ] && opsi-dev-cli -l 6 opsi-package --path=hwaudit-opsi-package set-value packageVersion "$package.$CI_JOB_ID"'
    - opsi-dev-cli -l 6 binary pull
    - opsi-makepackage --no-set-rights -l 6 hwaudit-opsi-package
    - upload-package hwaudit*.opsi
