image: python:3.7-stretch

stages:
  - build
  - package

build:linux-pyinstaller:
  stage: build
  script:
    - apt -y install curl
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
    - source $HOME/.poetry/env
    - poetry install
    - poetry run opsi-dev-tool -l info --pyinstaller-poetry-build
    - if test "$CI_COMMIT_TAG"; then poetry run opsi-dev-tool -l info --binary-push dist/opsi-hwaudit; fi
    - if ! test "$CI_COMMIT_TAG"; then poetry run opsi-dev-tool -l info --binary-push dist/opsi-hwaudit "$CI_JOB_ID"; fi
    - mv hwaudit hwaudit.src
    - cd dist
    - tar -czvf ../hwaudit_binaries.tar.gz .
  artifacts:
    name: 'hwaudit-linux-pyinstaller'
    paths:
      - hwaudit_binaries.tar.gz
    expire_in: 2 day

build:windows-pyinstaller:
  stage: build
  tags:
    - win10
  script:
    - pip install poetry
    - poetry remove mysqlclient
    - poetry add "deps/mysqlclient-1.4.6-cp37-cp37m-win32.whl"
    - poetry update
    - poetry run opsi-dev-tool -l info --pyinstaller-poetry-build
    - if (! $CI_COMMIT_TAG) {poetry run opsi-dev-tool -l info --binary-push dist/opsi-hwaudit.exe "$CI_JOB_ID"}
    - if ($CI_COMMIT_TAG) {poetry run opsi-dev-tool -l info --binary-push dist/opsi-hwaudit.exe}
    - Move-Item -Path hwaudit -Destination hwaudit.src -Force
    - Move-Item -Path dist\ -Destination hwaudit
  artifacts:
    name: 'hwaudit-windows-pyinstaller'
    paths:
      - opsi-hwaudit.exe
    expire_in: 2 day

build:osx-pyinstaller:
  stage: build
  tags:
    - macos
  script:
    - source $HOME/.poetry/env
    - poetry install
    - poetry run opsi-dev-tool -l info --pyinstaller-poetry-build
    - if test "$CI_COMMIT_TAG"; then poetry run opsi-dev-tool -l info --binary-push dist/opsi-hwaudit; fi
    - if ! test "$CI_COMMIT_TAG"; then poetry run opsi-dev-tool -l info --binary-push dist/opsi-hwaudit "$CI_JOB_ID"; fi
    - mv hwaudit hwaudit.src
    - mv dist/opsi-hwaudit .
  artifacts:
    name: 'hwaudit-macos-pyinstaller'
    paths:
      - opsi-hwaudit
    expire_in: 2 day

.install_opsi_utils: &install_opsi_utils |
  apt update
  apt -y install zsync librsync-dev cpio
  poetry run opsi-dev-tool --binary-pull development opsi-utils linux latest ./
  useradd opsiconfd
  groupadd pcpatch
  groupadd opsiadmin
  adduser opsiconfd pcpatch
  adduser opsiconfd opsiadmin

package:makeopsipackage:
  stage: package
  script:
    - apt -y install curl
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
    - source $HOME/.poetry/env
    - poetry install
    - poetry run opsi-dev-tool -l debug --binary-pull
    - export VERSION=`cat pyproject.toml | grep -e "^version = " | cut -d \" -f 2`
    - cd hwaudit-opsi-package
    - cat OPSI/control | awk -v new_version="$VERSION" '/^\[/ { section=$1} {line=$0; if ($1 == "version:" && section == "[Product]"){ line = $1 " " new_version} print line}' > tmp
    - cat tmp > OPSI/control
    - rm tmp
    - *install_opsi_utils
    - opsi-utils/opsi-makepackage
  artifacts:
    name: hwaudit-opsi-package
    paths:
      - "hwaudit-opsi-package/hwaudit_*-1.opsi"
