image: python:3.7-stretch

stages:
  - build
  - package

build:linux-pyinstaller:
  stage: build
  script:
    - apt -y install curl
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
    - source $HOME/.poetry/env
    - poetry install
    - poetry run opsi-dev-tool -l info --pyinstaller-poetry-build
    - mv hwaudit hwaudit.src
    - cd dist/hwaudit
    - tar -czvf ../../hwaudit_binaries.tar.gz .
  artifacts:
    name: 'hwaudit-linux-pyinstaller'
    paths:
      - hwaudit_binaries.tar.gz
    expire_in: 2 day

build:windows-pyinstaller:
  stage: build
  script:
    - pip install poetry
    - Get-Content pyproject.toml | %{ $_ -Replace '"^mysqlclient = .*"', 'mysqlclient = {path = "deps/mysqlclient-1.4.6-cp37-cp37m-win32.whl"}' } | Out-File -Encoding ASCII "pyproject.tmp"
    - Move-Item -Path "pyproject.tmp" -Destination "pyproject.toml" -Force
    - Get-Content pyproject.toml
    - poetry install
    - poetry run opsi-dev-tool -l debug --pyinstaller-poetry-build
    - Move-Item -Path opsiclientd -Destination opsiclientd.src -Force
    - Move-Item -Path dist\opsiclientd -Destination opsiclientd
  artifacts:
    name: 'opsiclientd-windows-pyinstaller'
    paths:
      - opsiclientd
    expire_in: 2 day
