[tool.poetry]
name = "hwaudit"
version = "4.2.0.0"
description = "opsi hardware audit"
homepage = "https://www.opsi.org"
license = "AGPL-3.0"
authors = ["uib GmbH <info@uib.de>"]
maintainers = ["uib GmbH <info@uib.de>"]

[[tool.poetry.source]]
name = "uib"
url = "https://pypi.uib.gmbh/simple/"

[tool.poetry.dependencies]
python = ">=3.7, <4.0"
argparse = "^1.4.0"
python-opsi = "^4.2.0"
#python-opsi = {path = "../python-opsi/"}
pywin32 = { version = "^227", platform = "win32" }
wmi  = { version = "^1.5.1", platform = "win32" }
mysqlclient = ">=1.4.6"	#"^1.4.6"
#mysqlclient = {path = "deps/mysqlclient-1.4.6-cp37-cp37m-win32.whl", platform = "win32"}

[tool.poetry.scripts]
hwaudit = "hwaudit.__main__:main"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
pywin32-ctypes = { version = "^0.2.0", platform = "win32" }
pefile = "^2019.4.18"
bs4 = "^0.0.1"
macholib = { version = "^1.14", platform="darwin" }
pyinstaller = "^4.0"
setuptools = "^50.3.0"
opsi-dev-tools = "^1.0.62"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
